backend:
  name: github
  repo: alnuqtamedia/alnuqta-media
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "المقالات والأخبار"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "الكاتب / المحرر", name: "author", widget: "string" }
      - { label: "الصورة الرئيسية / الميديا", name: "thumbnail", widget: "image", required: false }
      - { label: "محتوى التقرير أو المقال", name: "body", widget: "markdown" }
