backend:
  name: github
  repo: alnuqtamedia/alnuqta-media
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "المقالات والأخبار"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "محتوى التقرير", name: "body", widget: "markdown" }
